In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/digit-recognizer/train.csv
/kaggle/input/digit-recognizer/test.csv
/kaggle/input/digit-recognizer/sample_submission.csv


In [2]:
train_data = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')
train_data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [3]:
test_data = pd.read_csv('/kaggle/input/digit-recognizer/test.csv')
test_data.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [4]:
# X, Y
from sklearn import preprocessing
x = train_data.drop(['label'], axis=1)
y = train_data['label']

mm_scaler = preprocessing.MinMaxScaler()
x = pd.DataFrame(mm_scaler.fit_transform(x))
#print(x)

#x = x.dropna(axis=1,how='all')
x = x.fillna(0)
print(x.shape)

from sklearn.decomposition import PCA
pca = PCA(30)
pca.fit(x)
x = pca.transform(x)
print(type(x))
print(x)

# Divide into train and validation set
x_train = x[0:40000,:]
print(x_train.shape)
y_train = y.loc[0:39999]
print(y_train.shape)
x_validate = x[40000:42000,:]
print(x_validate.shape)
y_validate = y.loc[40000:41999]
print(y_validate.shape)


(42000, 784)
<class 'numpy.ndarray'>
[[-2.59449322 -2.74239731  0.71875289 ...  0.81864007  0.23128648
   0.31869737]
 [ 6.67235952 -1.41392745 -1.96786508 ...  0.04725265 -0.31452038
  -0.34468768]
 [-3.47801736 -1.15202264  0.2633542  ...  0.41801271 -0.04459143
   0.46416867]
 ...
 [ 1.31870578  3.72555025 -0.66119799 ...  0.18086909  0.867098
  -0.20467284]
 [ 1.28391919  0.24320023  2.7354372  ... -0.53693046  0.62640259
   0.3566769 ]
 [-1.42842822  1.64271767  0.24666594 ...  0.19861525  0.35946442
  -0.61301482]]
(40000, 30)
(40000,)
(2000, 30)
(2000,)


In [5]:
#classify with SVM
from sklearn import svm
from sklearn.metrics import accuracy_score, confusion_matrix

clf = svm.SVC(kernel='rbf', gamma='auto')
#fit the model to the train data
clf.fit(x_train, y_train)
#predict train data
pred_train = clf.predict(x_train)
#predict validate data
pred_validate = clf.predict(x_validate)
#print the results
train_accuracy_score = accuracy_score(y_train.to_numpy(), pred_train)
validate_accuracy_score = accuracy_score(y_validate.to_numpy(), pred_validate)
print(f"Train accuracy: {train_accuracy_score}, Validate accuracy: {validate_accuracy_score}")

#get the confusion matrix
print(confusion_matrix(y_validate.to_numpy(), pred_validate))

Train accuracy: 0.9902, Validate accuracy: 0.978
[[197   0   0   0   0   0   0   0   0   0]
 [  0 221   0   1   0   1   0   1   0   1]
 [  1   0 185   1   0   0   0   0   1   2]
 [  1   0   0 194   0   0   0   1   0   2]
 [  0   1   0   0 223   0   1   0   0   1]
 [  1   1   0   2   0 154   0   0   3   1]
 [  1   0   0   0   0   0 215   0   0   0]
 [  0   0   2   1   0   0   0 198   0   1]
 [  1   2   1   0   1   0   0   0 174   0]
 [  0   0   2   1   3   1   0   1   2 195]]


In [6]:
#Fit the model to x
clf.fit(x,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [7]:
# Preprocess test data

x_test = test_data
print(x_test.shape)

#Scale test data
x_test = pd.DataFrame(mm_scaler.transform(x_test))
print(x_test.shape)

test_data = x_test.fillna(0)
#test_data.replace(np.inf,0)
#print(test_data.isnull())
#print(type(test_data))

#pca.fit(test_data)
x_test = pca.transform(x_test)
#print(type(test_data))
print(x_test.shape)

(28000, 784)
(28000, 784)
(28000, 30)


In [8]:
# Predict the test data
pred_test = clf.predict(x_test)
pred_test = pd.Series(pred_test,name="Label")
output_test = pd.concat([pd.Series(range(1,28001),name = "ImageId"),pred_test],axis = 1)

#output_test = pd.DataFrame({'ImageId': x_test.label,'Label': pred_test})
output_test.to_csv('my_submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!
